conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/services/http/securing_httpd/httpd_configure_os_protect_web_server/httpd_restrict_file_dir_access/http_configure_log_file_ownership/rule.yml
description: 'All <tt>httpd</tt> logs must be owned by root user and group. By default,

  the path for httpd logs is <tt>/var/log/httpd/</tt>


  To properly set the owner of <code>/var/log/httpd</code>, run the command:

  <pre>$ sudo chown root /var/log/httpd </pre>


  To properly set the owner of <code>/var/log/httpd/*</code>, run the command:

  <pre>$ sudo chown root /var/log/httpd/* </pre>'
identifiers: {}
inherited_platforms: []
ocil: '

  To properly set the owner of <code>/var/log/httpd</code>, run the command:

  <pre>$ sudo chown root /var/log/httpd </pre>


  To properly set the owner of <code>/var/log/httpd/*</code>, run the command:

  <pre>$ sudo chown root /var/log/httpd/* </pre>'
ocil_clause: null
oval_external_content: null
platform: null
platforms: !!set {}
prodtype: rhel7,rhel8
rationale: 'A major tool in exploring the web site use, attempted use, unusual conditions,

  and problems are the access and error logs. In the event of a security incident,

  these logs can provide the SA and the web administrator with valuable

  information. Because of the information that is captured in the logs, it is

  critical that only authorized individuals have access to the logs.'
references:
  stigid: WG255
requires: []
severity: medium
template: null
title: HTTPD Log Files Must Be Owned By Root
warnings: []
