conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/system/auditing/policy_rules/audit_basic_configuration/rule.yml
description: 'Perform basic configuration of Audit system.

  Make sure that any previously defined rules are cleared, the auditing system is
  configured to handle sudden bursts of events, and in cases of failure, messages
  are configured to be directed to system log.


  The following rules configure audit as described above:

  <pre>## First rule - delete all

  -D


  ## Increase the buffers to survive stress events.

  ## Make this bigger for busy systems

  -b 8192


  ## This determine how long to wait in burst of events

  --backlog_wait_time 60000


  ## Set failure mode to syslog

  -f 1


  </pre>


  The <tt>Audit</tt> package provides pre-configured  rules in <tt>/usr/share/audit/sample-rules</tt>.
  The above content can be found in <tt>/usr/share/audit/sample-rules/10-base-config.rules</tt>.

  To deploy this configuration, it is recommended to copy it over to the <tt>/etc/audit/rules.d/</tt>
  directory:

  <pre>

  cp /usr/share/audit/sample-rules/10-base-config.rules /etc/audit/rules.d/

  </pre>


  Load new Audit rules into kernel by running:

  <pre>augenrules --load</pre>'
identifiers:
  cce: CCE-83670-0
inherited_platforms:
- machine
ocil: 'To verify that the <tt>Audit</tt> is correctly configured according to recommended
  rules, check the content of the file with the following command:

  <pre>cat /etc/audit/rules.d/10-base-config.rules</pre>

  The output has to be exactly as follows:

  <pre>## First rule - delete all

  -D


  ## Increase the buffers to survive stress events.

  ## Make this bigger for busy systems

  -b 8192


  ## This determine how long to wait in burst of events

  --backlog_wait_time 60000


  ## Set failure mode to syslog

  -f 1


  </pre>'
ocil_clause: the file does not exist or the content differs
oval_external_content: null
platform: null
platforms: !!set
  machine: null
prodtype: ol8,rhcos4,rhel8,rhel9
rationale: Without basic configurations, audit may not perform as expected. It may
  not be able to correctly handle events under stressful conditions, or log events
  in case of failure.
references:
  nist: AU-2(a)
  ospp: FAU_GEN.1.1.c
  srg: SRG-OS-000365-GPOS-00152,SRG-OS-000475-GPOS-00220
requires: []
severity: medium
template:
  backends: {}
  name: audit_file_contents
  vars:
    contents: '## First rule - delete all

      -D


      ## Increase the buffers to survive stress events.

      ## Make this bigger for busy systems

      -b 8192


      ## This determine how long to wait in burst of events

      --backlog_wait_time 60000


      ## Set failure mode to syslog

      -f 1


      '
    filepath: /etc/audit/rules.d/10-base-config.rules
title: Configure basic parameters of Audit system
warnings: []
