conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_rate_limiting/rule.yml
description: 'Create a direct firewall rule to protect against DoS attacks with the
  following

  command:

  <pre>$ sudo firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT_direct
  0 -p tcp -m limit --limit 25/minute --limit-burst 100  -j INPUT_ZONES</pre>'
identifiers: {}
inherited_platforms:
- machine
ocil: 'To verify the operating system protects against or limits the effects of DoS

  attacks by ensuring the operating system is implementing rate-limiting measures

  on impacted network interfaces, run the following command:

  <pre>$ sudo firewall-cmd --permanent --direct --get-rules ipv4 filter INPUT_direct</pre>

  The output should return:

  <pre>0 -p tcp -m limit --limit 25/minute --limit-burst 100 -j INPUT_ZONES</pre>'
ocil_clause: firewalld is not rate limiting connections
oval_external_content: null
platform: null
platforms: !!set
  machine: null
prodtype: ol7,rhel7,wrlinux1019
rationale: 'DoS is a condition when a resource is not available for legitimate users.
  When

  this occurs, the organization either cannot accomplish its mission or must

  operate at degraded capacity.

  <br /><br />

  This requirement addresses the configuration of

  the operating system to mitigate the impact of DoS attacks that have occurred or

  are ongoing on system availability. For each system, known and potential DoS

  attacks must be identified and solutions for each type implemented. A variety of

  technologies exist to limit or, in some cases, eliminate the effects of DoS

  attacks (e.g., limiting processes or establishing memory partitions). Employing

  increased capacity and bandwidth, combined with service redundancy, may reduce

  the susceptibility to some DoS attacks.'
references:
  disa: CCI-002385
  nist: SC-5,SC-5(1),SC-5(2),SC-5(3)(a),CM-6(a)
  srg: SRG-OS-000420-GPOS-00186
  stigid: OL07-00-040510
  vmmsrg: SRG-OS-000420-VMM-001690
requires: []
severity: medium
template: null
title: Configure firewalld To Rate Limit Connections
warnings: []
