# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Collect users with not correct maximum time period between password changes
  command: |
    awk -F: '$5 > 60 || $5 == "" {print $1}' /etc/shadow
  register: user_names
  tags:
    - CCE-85571-8
    - DISA-STIG-SLES-15-020230
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-5(1)(d)
    - NIST-800-53-IA-5(f)
    - accounts_password_set_max_life_existing
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy

- name: Change the maximum time period between password changes
  command: |
    chage -M 60 {{ item }}
  with_items: '{{ user_names.stdout_lines }}'
  when: user_names.stdout_lines | length > 0
  tags:
    - CCE-85571-8
    - DISA-STIG-SLES-15-020230
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-5(1)(d)
    - NIST-800-53-IA-5(f)
    - accounts_password_set_max_life_existing
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
