conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/rule.yml
description: 'Crypto Policies provide a centralized control over crypto algorithms
  usage of many packages.

  Kerberos is supported by crypto policy, but it''s configuration may be

  set up to ignore it.

  To check that Crypto Policies settings for Kerberos are configured correctly, examine
  that there is a symlink at

  /etc/krb5.conf.d/crypto-policies targeting /etc/cypto-policies/back-ends/krb5.config.

  If the symlink exists, kerberos is configured to use the system-wide crypto policy
  settings.'
identifiers: {}
inherited_platforms: []
ocil: 'Check that the symlink exists and target the correct kerberos crypto policy,
  with the following command:

  <pre>file /etc/krb5.conf.d/crypto-policies</pre>

  If command ouput shows the following line, kerberos is configured to use the system-wide
  crypto policy.

  <pre>/etc/krb5.conf.d/crypto-policies: symbolic link to /etc/crypto-policies/back-ends/krb5.config</pre>'
ocil_clause: the symlink does not exist or points to a different target
oval_external_content: null
platform: null
platforms: !!set {}
prodtype: fedora,ol8,rhcos4,rhel8,rhel9,rhv4
rationale: 'Overriding the system crypto policy makes the behavior of Kerberos violate
  expectations,

  and makes system configuration more fragmented.'
references:
  ism: 0418,1055,1402
  nerc-cip: CIP-003-3 R4.2,CIP-007-3 R5.1
  nist: SC-13,SC-12(2),SC-12(3)
  srg: SRG-OS-000120-GPOS-00061
requires: []
severity: medium
template: null
title: Configure Kerberos to use System Crypto Policy
warnings: []
