conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/rule.yml
description: 'Crypto Policies provide a centralized control over crypto algorithms
  usage of many packages.

  GnuTLS is supported by system crypto policy, but the GnuTLS configuration may be

  set up to ignore it.


  To check that Crypto Policies settings are configured correctly, ensure that

  <tt>/etc/crypto-policies/back-ends/gnutls.config</tt> contains the following

  line and is not commented out:

  <tt>+VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0</tt>'
identifiers: {}
inherited_platforms: []
ocil: 'To verify if GnuTLS uses defined DoD-approved TLS Crypto Policy, run:

  <pre>$ grep

  ''+VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0''

  /etc/crypto-policies/back-ends/gnutls.config</pre> and verify that a match exists.'
ocil_clause: cryptographic policy for gnutls is not configured or is configured incorrectly
oval_external_content: null
platform: null
platforms: !!set {}
prodtype: fedora,rhel8
rationale: 'Overriding the system crypto policy makes the behavior of the GnuTLS

  library violate expectations, and makes system configuration more

  fragmented.'
references:
  disa: CCI-001453
  nist: AC-17(2)
  srg: SRG-OS-000250-GPOS-00093,SRG-OS-000423-GPOS-00187
requires: []
severity: medium
template: null
title: Configure GnuTLS library to use DoD-approved TLS Encryption
warnings: []
