conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/system/logging/configure_logwatch_on_logserver/logwatch_configured_splithosts/rule.yml
description: 'If <tt>SplitHosts</tt> is set, Logwatch will separate entries by hostname.

  This makes the report longer but significantly more usable. If it is not

  set, then Logwatch will not report which host generated a given log entry,

  and that information is almost always necessary

  <pre> SplitHosts = yes </pre>'
identifiers: {}
inherited_platforms:
- machine
ocil: null
ocil_clause: null
oval_external_content: null
platform: null
platforms: !!set
  machine: null
prodtype: fedora,rhel7,rhel8
rationale: ''
references: {}
requires: []
severity: unknown
template: null
title: Configure Logwatch SplitHosts Line
warnings: []
