# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Enable service systemd-timesyncd
  block:

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Enable service systemd-timesyncd
      service:
        name: systemd-timesyncd
        enabled: 'yes'
        state: started
        masked: 'no'
      when:
        - '"systemd" in ansible_facts.packages'
  when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-10.4
    - enable_strategy
    - high_severity
    - low_complexity
    - low_disruption
    - no_reboot_needed
    - service_timesyncd_enabled
