# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Ensure sysctl kernel.sysrq is set to 0
  sysctl:
    name: "kernel.sysrq"
    value: "0"
    state: present
    reload: yes
