conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
description: 'Crypto Policies provide a centralized control over crypto algorithms
  usage of many packages.

  SSH is supported by crypto policy, but the SSH configuration may be

  set up to ignore it.

  To check that Crypto Policies settings are configured correctly, ensure that

  the <tt>CRYPTO_POLICY</tt> variable is either commented or not set at all

  in the <tt>/etc/sysconfig/sshd</tt>.'
identifiers:
  cce: CCE-85795-3
inherited_platforms: []
ocil: 'Check that the <tt>CRYPTO_POLICY</tt> variable is not set or is commented in
  the

  <tt>/etc/sysconfig/sshd</tt>.'
ocil_clause: the CRYPTO_POLICY variable is not set or is commented in the /etc/sysconfig/sshd
oval_external_content: null
platform: null
platforms: !!set {}
prodtype: fedora,ol8,rhcos4,rhel8,rhel9,rhv4,sle15
rationale: 'Overriding the system crypto policy makes the behavior of the SSH service
  violate expectations,

  and makes system configuration more fragmented.'
references:
  hipaa: 164.308(a)(4)(i),164.308(b)(1),164.308(b)(3),164.312(e)(1),164.312(e)(2)(ii)
  nerc-cip: CIP-003-3 R4.2,CIP-007-3 R5.1,CIP-007-3 R7.1
  nist: AC-17(a),AC-17(2),CM-6(a),MA-4(6),SC-13
  srg: SRG-OS-000250-GPOS-00093
requires: []
severity: medium
template: null
title: Configure SSH to use System Crypto Policy
warnings: []
