# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Gather the package facts
  package_facts:
    manager: auto
  tags:
    - CCE-83124-8
    - DISA-STIG-SLES-12-030300
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-AU-8(1)(b)
    - chronyd_or_ntpd_set_maxpoll
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
- (xccdf-var var_time_service_set_maxpoll)

- name: Check that /etc/ntp.conf exist
  stat:
    path: /etc/ntp.conf
  register: ntp_conf_exist_result
  when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
    - '"chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages'
  tags:
    - CCE-83124-8
    - DISA-STIG-SLES-12-030300
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-AU-8(1)(b)
    - chronyd_or_ntpd_set_maxpoll
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy

- name: Check that /etc/chrony.conf exist
  stat:
    path: /etc/chrony.conf
  register: chrony_conf_exist_result
  when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
    - '"chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages'
  tags:
    - CCE-83124-8
    - DISA-STIG-SLES-12-030300
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-AU-8(1)(b)
    - chronyd_or_ntpd_set_maxpoll
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy

- name: Update the maxpoll values in /etc/ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    regex: ^(server.*maxpoll) [0-9]+(\s+.*)$
    line: \1 {{ var_time_service_set_maxpoll }}\2
    backrefs: true
  when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
    - '"chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages'
    - ntp_conf_exist_result.stat.exists
  tags:
    - CCE-83124-8
    - DISA-STIG-SLES-12-030300
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-AU-8(1)(b)
    - chronyd_or_ntpd_set_maxpoll
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy

- name: Update the maxpoll values in /etc/chrony.conf
  lineinfile:
    path: /etc/chrony.conf
    regex: ^(server.*maxpoll) [0-9]+(\s+.*)$
    line: \1 {{ var_time_service_set_maxpoll }}\2
    backrefs: true
  when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
    - '"chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages'
    - chrony_conf_exist_result.stat.exists
  tags:
    - CCE-83124-8
    - DISA-STIG-SLES-12-030300
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-AU-8(1)(b)
    - chronyd_or_ntpd_set_maxpoll
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy

- name: Set the maxpoll values in /etc/ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    regex: (^server\s+((?!maxpoll).)*)$
    line: \1 maxpoll {{ var_time_service_set_maxpoll }}\n
    backrefs: true
  when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
    - '"chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages'
    - ntp_conf_exist_result.stat.exists
  tags:
    - CCE-83124-8
    - DISA-STIG-SLES-12-030300
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-AU-8(1)(b)
    - chronyd_or_ntpd_set_maxpoll
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy

- name: Set the maxpoll values in /etc/chrony.conf
  lineinfile:
    path: /etc/chrony.conf
    regex: (^server\s+((?!maxpoll).)*)$
    line: \1 maxpoll {{ var_time_service_set_maxpoll }}\n
    backrefs: true
  when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
    - '"chrony" in ansible_facts.packages or "ntp" in ansible_facts.packages'
    - chrony_conf_exist_result.stat.exists
  tags:
    - CCE-83124-8
    - DISA-STIG-SLES-12-030300
    - NIST-800-53-AU-8(1)(a)
    - NIST-800-53-AU-8(1)(b)
    - chronyd_or_ntpd_set_maxpoll
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
