# platform = Java Runtime Environment
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure Java Deployment Directory Exists
  file:
    path: /etc/.java/deployment
    state: directory
    mode: '0755'
  tags:
    - DISA-STIG-JRE8-UX-000090
    - NIST-800-53-SC-18 (3)
    - configure_strategy
    - java_jre_lock_untrusted_sources_locked
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed

- name: Disable User Access to Locking Untrusted Sources Setting
  lineinfile:
    create: true
    mode: '0644'
    dest: /etc/.java/deployment/deployment.properties
    regexp: ^\s*#?\s*deployment.security.askgrantdialog.show.locked
    line: deployment.security.askgrantdialog.show.locked
  tags:
    - DISA-STIG-JRE8-UX-000090
    - NIST-800-53-SC-18 (3)
    - configure_strategy
    - java_jre_lock_untrusted_sources_locked
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
