# platform = Java Runtime Environment
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure Java Deployment Directory Exists
  file:
    path: /etc/.java/deployment
    state: directory
    mode: '0755'
  tags:
    - DISA-STIG-JRE8-UX-000160
    - NIST-800-53-IA-5(2)(d)
    - configure_strategy
    - java_jre_security_revocation_check
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed

- name: Enable Revocation Checks for Publisher Certificates
  lineinfile:
    create: true
    mode: '0644'
    dest: /etc/.java/deployment/deployment.properties
    regexp: ^\s*#?\s*deployment.security.revocation.check=.*
    line: deployment.security.revocation.check=ALL_CERTIFICATES
  tags:
    - DISA-STIG-JRE8-UX-000160
    - NIST-800-53-IA-5(2)(d)
    - configure_strategy
    - java_jre_security_revocation_check
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
