# platform = Java Runtime Environment
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure Java Deployment Directory Exists
  file:
    path: /etc/.java/deployment
    state: directory
    mode: '0755'
  tags:
    - DISA-STIG-JRE8-UX-000110
    - NIST-800-53-SC-18(3)
    - configure_strategy
    - java_jre_blacklist_check
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed

- name: Prevent the Download of Prohibited Mobile Code
  lineinfile:
    create: true
    mode: '0644'
    dest: /etc/.java/deployment/deployment.properties
    regexp: ^\s*#?\s*deployment.security.blacklist.check=.*
    line: deployment.security.blacklist.check=true
  tags:
    - DISA-STIG-JRE8-UX-000110
    - NIST-800-53-SC-18(3)
    - configure_strategy
    - java_jre_blacklist_check
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
