# platform = Java Runtime Environment
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure Java Deployment Directory Exists
  file:
    path: /etc/.java/deployment
    state: directory
    mode: '0755'
  tags:
    - DISA-STIG-JRE8-UX-000100
    - NIST-800-53-IA-5(2)(a)
    - configure_strategy
    - java_jre_validation_ocsp_locked
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed

- name: Disable User Access to Online Certificate Validation Setting
  lineinfile:
    create: true
    mode: '0644'
    dest: /etc/.java/deployment/deployment.properties
    regexp: ^\s*#?\s*deployment.security.validation.ocsp.locked
    line: deployment.security.validation.ocsp.locked
  tags:
    - DISA-STIG-JRE8-UX-000100
    - NIST-800-53-IA-5(2)(a)
    - configure_strategy
    - java_jre_validation_ocsp_locked
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
