# platform = Java Runtime Environment
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure Java Deployment Directory Exists
  file:
    path: /etc/.java/deployment
    state: directory
    mode: '0755'
  tags:
    - DISA-STIG-JRE8-UX-000080
    - NIST-800-53-SC-18 (3)
    - configure_strategy
    - java_jre_disable_untrusted_sources
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed

- name: Disable Execution of Signed Java Applets From Untrusted Sources Setting
  lineinfile:
    create: true
    mode: '0644'
    dest: /etc/.java/deployment/deployment.properties
    regexp: ^\s*#?\s*deployment.security.askgrantdialog.notinca=.*
    line: deployment.security.askgrantdialog.notinca=false
  tags:
    - DISA-STIG-JRE8-UX-000080
    - NIST-800-53-SC-18 (3)
    - configure_strategy
    - java_jre_disable_untrusted_sources
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
