# platform = Java Runtime Environment
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
- name: Ensure Java Deployment Directory Exists
  file:
    path: /etc/.java/deployment
    state: directory
    mode: '0755'
  tags:
    - DISA-STIG-JRE8-UX-000130
    - NIST-800-53-CM-7(5)(b)
    - configure_strategy
    - java_jre_accepted_sites_exists
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed

- name: Ensure Java exception.sites File Exists
  file:
    path: /etc/.java/deployment/exception.sites
    state: touch
    mode: '0644'
  tags:
    - DISA-STIG-JRE8-UX-000130
    - NIST-800-53-CM-7(5)(b)
    - configure_strategy
    - java_jre_accepted_sites_exists
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
