# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low


- name: Find /etc/audit/rules.d/ file(s)
  find:
    paths: "/etc/audit/rules.d/"
    patterns: "^.*rules$"
    use_regex: yes
  register: files_found

- name: Set permissions for /etc/audit/rules.d/ file(s)
  file:
    path: "{{ item.path }}"
    mode: "0640"
  with_items:
    - "{{ files_found.files }}"

