# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: Ensure sysctl vm.mmap_min_addr is set to 65536
  sysctl:
    name: "vm.mmap_min_addr"
    value: "65536"
    state: present
    reload: yes
