# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- (xccdf-var sysctl_net_ipv6_conf_default_max_addresses_value)

- name: Ensure sysctl net.ipv6.conf.default.max_addresses is set
  sysctl:
    name: "net.ipv6.conf.default.max_addresses"
    value: "{{ sysctl_net_ipv6_conf_default_max_addresses_value }}"
    state: present
    reload: yes
