conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/services/http/securing_httpd/httpd_modules_improve_security/httpd_deploy_mod_security/httpd_install_mod_security/rule.yml
description: 'Install the <tt>security</tt> module:

  The <code>mod_security</code> package can be installed with the following command:

  <pre>

  $ sudo yum install mod_security</pre>'
identifiers:
  cce: CCE-80321-3
inherited_platforms: []
ocil: null
ocil_clause: null
oval_external_content: null
platform: null
platforms: !!set {}
prodtype: rhel7,rhel8
rationale: '<tt>mod_security</tt> provides an additional level of protection for the
  web server by

  enabling the administrator to implement content access policies and filters at the

  application layer.'
references: {}
requires: []
severity: unknown
template: null
title: Install mod_security
warnings: []
