# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Ensure libpam-pwquality is installed
  package:
    name: libpam-pwquality
    state: present
  tags:
    - DISA-STIG-UBTU-20-010057
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_pam_pwquality_installed
