# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Ensure vlock is installed
  package:
    name: vlock
    state: present
  tags:
    - DISA-STIG-UBTU-20-010005
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - vlock_installed
