conflicts: []
definition_location: /home/chase/_work/complianceascode-content/complianceascode-content/linux_os/guide/system/accounts/accounts-pam/pam_disable_automatic_configuration/rule.yml
description: 'Verify the SUSE operating system is configured to not overwrite Pluggable

  Authentication Modules (PAM) configuration on package changes.'
identifiers:
  cce: CCE-83113-1
inherited_platforms: []
ocil: 'Check that soft links between PAM configuration files are removed with the
  following command:


  <pre># find /etc/pam.d/ -type l -iname "common-*"</pre>


  If any results are returned, this is a finding.'
ocil_clause: that is not the case
oval_external_content: null
platform: null
platforms: !!set {}
prodtype: sle12,sle15
rationale: '<tt>pam-config</tt> is a command line utility that automatically generates

  a system PAM configuration as packages are installed, updated or removed

  from the system. <tt>pam-config</tt> removes configurations for PAM modules

  and parameters that it does not know about. It may render ineffective PAM

  configuration by the system administrator and thus impact system security.'
references:
  disa: CCI-000366
  nist: CM-6(b),CM-6.1(iv)
  srg: SRG-OS-000480-GPOS-00227
  stigid: SLES-12-010910
requires: []
severity: medium
template: null
title: The PAM configuration should not be changed automatically
warnings: []
