# platform = multi_platform_all
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Ensure usbguard is installed
  package:
    name: usbguard
    state: present
  tags:
    - CCE-82959-8
    - DISA-STIG-RHEL-08-040139
    - enable_strategy
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - package_usbguard_installed
